### ISSUE TITLE
Using with nuxt.js

### ISSUE THREAD

**Issue by narduin** [niklashaug/vue-carbonbadge#1]
Hello!

I'm trying to use vue-carbonbadge on a [nuxt](https://nuxtjs.org/) project.
I added the dependency with yarn but then I'm a little lost because nuxt can't seem to find the component and nothing is displayed.
I tried to register it as a plugin but no luck.

Any idea?
Thank you!

**Comment by narduin** [comment]
Alright nevermind I found out, sorry.
If anyone is wondering:

Create a vue-carbon-badge.js file inside the plugins folder:
```js
// plugins/vue-carbon-badge.js

import Vue from 'vue'
import CarbonBadge from 'vue-carbonbadge'

Vue.use(CarbonBadge)
```

Then register the plugin globally in nuxt.config.js:
```js
plugins: [{ src: '~/plugins/vue-carbon-badge.js' }],
```

Use as instructed :)

**Comment by niklashaug** [comment]
@narduin No worries, thank you for sharing!
